<ul class="emojis">
    <li class="emoji" data-clipboard-text="--1">💖</li>
    <li class="emoji" data-clipboard-text="-1">😍</li>
    <li class="emoji" data-clipboard-text="100">🥰</li>
    <li class="emoji" data-clipboard-text="1234">😇</li>
    <li class="emoji" data-clipboard-text="8ball">😊</li>
    <li class="emoji" data-clipboard-text="a">😉</li>
    <li class="emoji" data-clipboard-text="ab">🙃</li>
    <li class="emoji" data-clipboard-text="abc">🙂</li>
    <li class="emoji" data-clipboard-text="abcd">😂</li>
    <li class="emoji" data-clipboard-text="accept">🤣</li>
    <li class="emoji" data-clipboard-text="aerial_tramway">😅</li>
    <li class="emoji" data-clipboard-text="airplane">😆</li>
    <li class="emoji" data-clipboard-text="alarm_clock">😀</li>
    <li class="emoji" data-clipboard-text="alien">😘</li>
    <li class="emoji" data-clipboard-text="ambulance">😗</li>
    <li class="emoji" data-clipboard-text="anchor">😚</li>
    <li class="emoji" data-clipboard-text="angel">😋</li>
    <li class="emoji" data-clipboard-text="anger">😐</li>
    <li class="emoji" data-clipboard-text="angry">🤨</li>
    <li class="emoji" data-clipboard-text="anguished">🤭</li>
    <li class="emoji" data-clipboard-text="ant">🤗</li>
    <li class="emoji" data-clipboard-text="apple">🤪</li>
    <li class="emoji" data-clipboard-text="aquarius">😜</li>
    <li class="emoji" data-clipboard-text="aries">😛</li>
    <li class="emoji" data-clipboard-text="arrow_backward">😷</li>
    <li class="emoji" data-clipboard-text="arrow_double_down">😪</li>
    <li class="emoji" data-clipboard-text="arrow_double_up">🤤</li>
    <li class="emoji" data-clipboard-text="arrow_down">🙄</li>
    <li class="emoji" data-clipboard-text="arrow_down_small">😒</li>
    <li class="emoji" data-clipboard-text="arrow_forward">😏</li>
    <li class="emoji" data-clipboard-text="arrow_heading_down">😑</li>
    <li class="emoji" data-clipboard-text="arrow_heading_up">😐</li>
    <li class="emoji" data-clipboard-text="arrow_left">😎</li>
    <li class="emoji" data-clipboard-text="arrow_lower_left">🤓</li>
    <li class="emoji" data-clipboard-text="arrow_lower_right">😢</li>
    <li class="emoji" data-clipboard-text="arrow_right">😥</li>
    <li class="emoji" data-clipboard-text="arrow_right_hook">😦</li>
    <li class="emoji" data-clipboard-text="arrow_up">😠</li>
    <li class="emoji" data-clipboard-text="arrow_up_down">😡</li>
    <li class="emoji" data-clipboard-text="arrow_up_small">🥱</li>
    <li class="emoji" data-clipboard-text="arrow_upper_left">😫</li>
    <li class="emoji" data-clipboard-text="arrow_upper_right">👍</li>
    <li class="emoji" data-clipboard-text="arrows_clockwise">👎</li>
    <li class="emoji" data-clipboard-text="arrows_counterclockwise">🖕</li>
    <li class="emoji" data-clipboard-text="art">💋</li>
    <li class="emoji" data-clipboard-text="articulated_lorry">🍒</li>
    <li class="emoji" data-clipboard-text="astonished">🍆</li>
    <li class="emoji" data-clipboard-text="atm">🧇</li>
    <li class="emoji" data-clipboard-text="b">🍕</li>
    <li class="emoji" data-clipboard-text="cat">🐈</li>
    <li class="emoji" data-clipboard-text="b">🐱</li>
    <li class="emoji" data-clipboard-text="b">🦄</li>
</ul>